testing worflow with single compose file

diff --git a/.github/workflows/ghactions.yml b/.github/workflows/ghactions.yml
--- a/.github/workflows/ghactions.yml
+++ b/.github/workflows/ghactions.yml
@@ -60,70 +60,91 @@ jobs:
           registry: ghcr.io
           username: ${{ secrets.GHCR_ACCES_TEST_USER}} #My personal access token so not usable for long term
           password: ${{ secrets.GHCR_ACCES_TEST_TOKEN }} 
-            
-      - name: Build and run backend containers
-        run: docker-compose -f docker-compose-start-backend.yml up -d
-
-      - name: Log container status
-        run: docker ps
-
-      - name: Wait for Backend to be Ready
+      - name: Build and run containers
+        run: |
+            docker-compose -f docker-compose.yml up --build -d
+    
+      - name: Wait for backend to be ready
         run: |
           echo "Waiting for backend service to be ready..."
-          success=false
-          for i in {1..30}; do # tries 30 times at an interval of 10 seconds
-            response=$(curl -o /dev/null -s -w "%{http_code}\n" -v http://localhost:3002/health || true)
-            if [ "$response" = "200" ]; then
-              echo "Backend service is ready."
-              success=true
-              break
-            else
-              echo "Attempt $i: Backend service not ready. Curl response: $response"
-              echo "Waiting for another 10 seconds..."
-            fi
-            sleep 10
+          until [ "$(docker inspect -f {{.State.Health.Status}} efilibrary-backend)" == "healthy" ]; do 
+            sleep 10;
+            echo "Waiting for backend service...";
           done
-          
-          if [ "$success" = false ] ; then
-            echo "Backend service did not become ready in time"
-            exit 1
-          fi
-        
-      
-      - name: Start frontend
-        run: docker-compose -f docker-compose-start-frontend.yml up -d
-      
-      - name: Install wait-on
-        run: npm install -g wait-on
-        
-      - name: Wait for Frontend to be Ready
+          echo "Backend service is ready."
+  
+      - name: Run frontend tests
         run: |
-          echo "Waiting for frontend service to be ready..."
-          success=false
-          for i in {1..30}; do # tries 30 times at an interval of 10 seconds
-            response=$(curl -o /dev/null -s -w "%{http_code}\n" -v http://localhost:3000)
-            if [ "$response" = "200" ]; then
-              echo "Backend service is ready."
-              success=true
-              break
-            else
-              echo "Attempt $i: Backend service not ready. Curl response: $response"
-              echo "Waiting for another 10 seconds..."
-            fi
-            sleep 10
-          done
-          if [ "$success" = false ] ; then
-            echo "Backend service did not become ready in time"
-            exit 1
-          fi
-
-      - name: Run tests 
-        run: docker exec -i efilibrary-frontend npm run dockertests
-
+          docker logs docker-robot -f
+  
       - name: Clean up
         if: always()
         run: |
-          docker-compose -f docker-compose-start-backend.yml down
-          docker-compose -f docker-compose-start-frontend.yml down
+          docker-compose -f docker-compose.yml down    
+            
+    #  - name: Build and run backend containers
+    #    run: docker-compose -f docker-compose-start-backend.yml up -d
+#
+    #  - name: Log container status
+    #    run: docker ps
+#
+    #  - name: Wait for Backend to be Ready
+    #    run: |
+    #      echo "Waiting for backend service to be ready..."
+    #      success=false
+    #      for i in {1..30}; do # tries 30 times at an interval of 10 seconds
+    #        response=$(curl -o /dev/null -s -w "%{http_code}\n" -v http://localhost:3002/health || true)
+    #        if [ "$response" = "200" ]; then
+    #          echo "Backend service is ready."
+    #          success=true
+    #          break
+    #        else
+    #          echo "Attempt $i: Backend service not ready. Curl response: $response"
+    #          echo "Waiting for another 10 seconds..."
+    #        fi
+    #        sleep 10
+    #      done
+    #      
+    #      if [ "$success" = false ] ; then
+    #        echo "Backend service did not become ready in time"
+    #        exit 1
+    #      fi
+    #    
+    #  
+    #  - name: Start frontend
+    #    run: docker-compose -f docker-compose-start-frontend.yml up -d
+    #  
+    #  - name: Install wait-on
+    #    run: npm install -g wait-on
+    #    
+    #  - name: Wait for Frontend to be Ready
+    #    run: |
+    #      echo "Waiting for frontend service to be ready..."
+    #      success=false
+    #      for i in {1..30}; do # tries 30 times at an interval of 10 seconds
+    #        response=$(curl -o /dev/null -s -w "%{http_code}\n" -v http://localhost:3000)
+    #        if [ "$response" = "200" ]; then
+    #          echo "Frontend service is ready."
+    #          success=true
+    #          break
+    #        else
+    #          echo "Attempt $i: Backend service not ready. Curl response: $response"
+    #          echo "Waiting for another 10 seconds..."
+    #        fi
+    #        sleep 10
+    #      done
+    #      if [ "$success" = false ] ; then
+    #        echo "Backend service did not become ready in time"
+    #        exit 1
+    #      fi
+#
+    #  - name: Run tests 
+    #    run: docker exec -i efilibrary-frontend npm run dockertests
+#
+    #  - name: Clean up
+    #    if: always()
+    #    run: |
+    #      docker-compose -f docker-compose-start-backend.yml down
+    #      docker-compose -f docker-compose-start-frontend.yml down
           
           
